/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yaml_client.gui;

import Person.Person;
import java.util.Observable;
import java.util.Observer;
import yaml_client.YAMLClientThread;
import yaml_client.YAML_Client;

/**
 *
 * @author Team 03
 */
public class FPerson extends javax.swing.JFrame implements Observer {

    YAMLClientThread clientThread;

    /**
     * Creates new form Person
     */
    public FPerson(YAMLClientThread yamlClient) {
        initComponents();
        clientThread = yamlClient;
        yamlClient.addObserver(this); //Pa que empiece a observar.

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblBMI = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(300, 460));
        setPreferredSize(new java.awt.Dimension(355, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("YAML TEST INTERFACE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel3.setText("Weight: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel4.setText("Height:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        txtWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWeightKeyTyped(evt);
            }
        });
        getContentPane().add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 150, -1));

        txtHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHeightKeyTyped(evt);
            }
        });
        getContentPane().add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 150, -1));

        btnOK.setBackground(new java.awt.Color(0, 204, 204));
        btnOK.setText("OK!");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 120, 70));

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel5.setText("BMI:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lblBMI.setBackground(new java.awt.Color(255, 204, 51));
        lblBMI.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        getContentPane().add(lblBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 150, 20));

        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel6.setText("Result: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        lblResult.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        getContentPane().add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 150, 20));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 360, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed

        Person person = new Person();
        person.setName(txtName.getText());
        person.setHeight(Double.parseDouble(txtHeight.getText()));
        person.setWeight(Double.parseDouble(txtWeight.getText()));

        clientThread.sendRequest(person);


    }//GEN-LAST:event_btnOKActionPerformed

    private void txtWeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWeightKeyTyped
        char a = evt.getKeyChar();
        if (Character.isLetter(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtWeightKeyTyped

    private void txtHeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeightKeyTyped
        char a = evt.getKeyChar();
        if (Character.isLetter(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtHeightKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblBMI;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        Person person = (Person) o1;
        if (o1 != null) {
            lblBMI.setText(String.valueOf(person.getBmi()));
            lblResult.setText(person.getResult());
        }

    }
}
